services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: projectdb
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/Admin/IdeaProjects/mariadb_data:/var/lib/mysql
    restart: always

volumes:
  mariadb_data: