server:
  port: 8080

spring:
  application:
    name: backend

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/projectdb
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update